### ISSUE TITLE
Deboggage USB error

### ISSUE THREAD

**Issue by SimonNarduzzi** [SimonNarduzzi/Vesperas#1]
No apk changes detected. Skipping file upload, force stopping package instead.
DEVICE SHELL COMMAND: am force-stop com.example.simon.vesperas
Launching application: com.example.simon.vesperas/com.example.simon.vesperas.MainActivity.
DEVICE SHELL COMMAND: am start -n "com.example.simon.vesperas/com.example.simon.vesperas.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.example.simon.vesperas/.MainActivity }
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.example.simon.vesperas/.MainActivity } from null (pid=17257, uid=2000) not exported from uid 10308
at android.os.Parcel.readException(Parcel.java:1540)
at android.os.Parcel.readException(Parcel.java:1493)
at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:2586)
at com.android.commands.am.Am.runStart(Am.java:768)
at com.android.commands.am.Am.onRun(Am.java:307)
at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
at com.android.commands.am.Am.main(Am.java:102)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:255)

**Comment by SimonNarduzzi** [comment]
Réglé avec le commit d763d6f48283999fa37f451572cc2ae59b2a796b
AndroidManifest.xml ne savait pas quelle classe lancer au démarrage.
